# Generated by Django 5.2.3 on 2025-08-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_phone_number_1_alter_user_phone_number_2'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrators', models.ManyToManyField(related_name='routes_as_admin', to='accounts.adminprofile')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='cities_light.city')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_as_collector', to='accounts.collectorprofile')),
            ],
        ),
    ]
