# Generated by Django 5.2.3 on 2026-03-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='collector',
        ),
    ]
