# Generated by Django 5.2.3 on 2025-07-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
