# Generated by Django 5.2.3 on 2025-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number_1_alter_user_phone_number_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
