# Generated by Django 5.2.3 on 2026-01-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_managerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('COLLECTOR', 'Collector'), ('MANAGER', 'Manager'), ('CLIENT', 'Client')], default='CLIENT', max_length=9),
        ),
    ]
