# Generated by Django 5.2.3 on 2026-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number_1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
