# Generated by Django 5.2.3 on 2026-03-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_phone_number_1_alter_user_phone_number_2'),
        ('routes', '0003_remove_route_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='collector',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='routes.route'),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_profile', to='routes.route'),
        ),
    ]
