# Generated by Django 5.2.3 on 2026-03-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_client_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='visit_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
