# Generated by Django 5.2.3 on 2025-10-30 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='associated_profile',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_associated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='maker',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ROUTE_INITIAL', 'Route initial'), ('ROUTE_REFUND', 'Route refund'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_PAYMENT', 'Loan payment'), ('ADJUSTMENT', 'Adjustment'), ('EXPENSE', 'Expense'), ('CASH_OUT', 'Cash out')], editable=False, max_length=50),
        ),
    ]
