# Generated by Django 5.2.3 on 2026-02-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_updated_at_transaction_voided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ROUTE_INITIAL', 'Route initial'), ('ROUTE_REFUND', 'Route refund'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_PAYMENT', 'Loan payment'), ('PAYMENT_VOID', 'Payment void'), ('ADJUSTMENT', 'Adjustment'), ('EXPENSE', 'Expense'), ('CASH_OUT', 'Cash out')], editable=False, max_length=50),
        ),
    ]
