# Generated by Django 5.2.3 on 2026-01-25 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_managerprofile'),
        ('routes', '0002_route_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest_rate', models.DecimalField(choices=[('0', '0%'), ('10', '10%'), ('20', '20%')], decimal_places=2, help_text='Tasa de interés permitida: 0%, 10% o 20%', max_digits=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='accounts.clientprofile')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectors', to='accounts.collectorprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='routes.route')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['created_at'],
            },
        ),
    ]
