# Generated by Django 5.2.3 on 2026-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installments',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de cuotas (mínimo 1, máximo 90)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_frequency',
            field=models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='WEEKLY', help_text='Frecuencia de pagos: Diaria, Semanal o Mensual', max_length=10),
        ),
    ]
