"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    'django-insecure-y%itquv^7=0=&m90lv(zi(oq4%0vd8p49-tywo^o@oqu8zsm#5'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False").lower() in ("true", "1", "yes")
CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if os.environ.get("CORS_ALLOWED_ORIGINS") else []

if os.environ.get("CSRF_TRUSTED_ORIGINS", None):
    CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(
        ",")

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-Party Apps
    'graphene_django',
    'django_extensions',
    "corsheaders",
    "cities_light",
    'django_filters',

    # Custom Apps
    'accounts.apps.AccountsConfig',
    'routes.apps.RoutesConfig',
    'transactions.apps.TransactionsConfig',
    'loans.apps.LoansConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GRAPHENE = {
    'SCHEMA': "api.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
    ],
}

AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
]

SHELL_PLUS = "ipython"

#CITIES LIGHT

CITIES_LIGHT_INCLUDE_COUNTRIES = ['CL']

UNFOLD = {
    "SITE_TITLE": "Vendetta",
    "SITE_HEADER": "Vendetta Admin",
    "NAVIGATION": [
        {
            "title": "Users",
            "items": [
                {
                    "title": "Users",
                    "icon": "people",
                    "link": reverse_lazy("admin:accounts_user_changelist"),
                },
                {
                    "title": "Invitation Codes",
                    "icon": "key",
                    "link": reverse_lazy("admin:accounts_invitationcode_changelist"),
                },
            ],
        },
        {
            "title": "Routes",
            "items": [
                {
                    "title": "Routes",
                    "icon": "map",
                    "link": reverse_lazy("admin:routes_route_changelist"),
                },
            ],
        },
        {
            "title": "Loans",
            "items": [
                {
                    "title": "Loans",
                    "icon": "request_quote",
                    "link": reverse_lazy("admin:loans_loan_changelist"),
                },
                {
                    "title": "Payments",
                    "icon": "receipt_long",
                    "link": reverse_lazy("admin:loans_payment_changelist"),
                },
            ],
        },
        {
            "title": "Audit",
            "items": [
                {
                    "title": "Transactions",
                    "icon": "history",
                    "link": reverse_lazy("admin:transactions_transaction_changelist"),
                },
            ],
        },
    ],
    "COLORS": {
        "primary": {
            "50": "243 248 232",
            "100": "228 240 206",
            "200": "198 224 156",
            "300": "159 201 94",
            "400": "120 174 42",
            "500": "90 138 24",
            "600": "53 83 14",
            "700": "41 66 9",
            "800": "30 48 7",
            "900": "19 31 4",
            "950": "10 17 2",
        },
    },
}

